// Generated by scripts/capture-hero-film.mjs and encode-hero-film.mjs.
export type HeroFilmScene = 'documents' | 'search' | 'chat' | 'sources' | 'vectors';
export type HeroSemanticWord = 'Ask' | 'Search' | 'Trace' | 'Inspect';
export const heroFilmChapters: Record<'desktop-light' | 'desktop-dark' | 'mobile-light' | 'mobile-dark',
  { scene: HeroFilmScene; word: HeroSemanticWord; start: number }[]> = {
  "desktop-light": [
    {
      "scene": "documents",
      "word": "Ask",
      "start": 0
    },
    {
      "scene": "search",
      "word": "Search",
      "start": 4
    },
    {
      "scene": "chat",
      "word": "Ask",
      "start": 7
    },
    {
      "scene": "sources",
      "word": "Trace",
      "start": 9.5
    },
    {
      "scene": "vectors",
      "word": "Inspect",
      "start": 11.5
    },
    {
      "scene": "documents",
      "word": "Ask",
      "start": 14.5
    }
  ],
  "mobile-light": [
    {
      "scene": "documents",
      "word": "Ask",
      "start": 0
    },
    {
      "scene": "search",
      "word": "Search",
      "start": 4
    },
    {
      "scene": "chat",
      "word": "Ask",
      "start": 7
    },
    {
      "scene": "sources",
      "word": "Trace",
      "start": 9.5
    },
    {
      "scene": "vectors",
      "word": "Inspect",
      "start": 11.5
    },
    {
      "scene": "documents",
      "word": "Ask",
      "start": 14.5
    }
  ],
  "desktop-dark": [
    {
      "scene": "documents",
      "word": "Ask",
      "start": 0
    },
    {
      "scene": "search",
      "word": "Search",
      "start": 4
    },
    {
      "scene": "chat",
      "word": "Ask",
      "start": 7
    },
    {
      "scene": "sources",
      "word": "Trace",
      "start": 9.5
    },
    {
      "scene": "vectors",
      "word": "Inspect",
      "start": 11.5
    },
    {
      "scene": "documents",
      "word": "Ask",
      "start": 14.5
    }
  ],
  "mobile-dark": [
    {
      "scene": "documents",
      "word": "Ask",
      "start": 0
    },
    {
      "scene": "search",
      "word": "Search",
      "start": 4
    },
    {
      "scene": "chat",
      "word": "Ask",
      "start": 7
    },
    {
      "scene": "sources",
      "word": "Trace",
      "start": 9.5
    },
    {
      "scene": "vectors",
      "word": "Inspect",
      "start": 11.5
    },
    {
      "scene": "documents",
      "word": "Ask",
      "start": 14.5
    }
  ]
};
